<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="true" canvasSize="1024,1024"/>
  <items>
    <item label="achievement_crown" file="/Users/workspace/taptitans/client/res_raw/texture/common/achievement_crown.png"/>
    <item label="achievement_star_off" file="/Users/workspace/taptitans/client/res_raw/texture/common/achievement_star_off.png"/>
    <item label="achievement_star_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/achievement_star_on.png"/>
    <item label="attack_buff_label" file="/Users/workspace/taptitans/client/res_raw/texture/common/attack_buff_label.png"/>
    <item label="bottom_bar" file="/Users/workspace/taptitans/client/res_raw/texture/common/bottom_bar.png"/>
    <item label="bottom_red_bar" file="/Users/workspace/taptitans/client/res_raw/texture/common/bottom_red_bar.png"/>
    <item label="btn_activity" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_activity.png"/>
    <item label="btn_big_blue" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_big_blue.png"/>
    <item label="btn_big_yellow" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_big_yellow.png"/>
    <item label="btn_blue" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_blue.png"/>
    <item label="btn_challenge" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_challenge.png"/>
    <item label="btn_challenge_boss" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_challenge_boss.png"/>
    <item label="btn_dailyreward" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_dailyreward.png"/>
    <item label="btn_daliy_relic" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_daliy_relic.png"/>
    <item label="btn_disabled" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_disabled.png"/>
    <item label="btn_equip_entry" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_equip_entry.png"/>
    <item label="btn_get_diamond" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_get_diamond.png"/>
    <item label="btn_get_supdiamond" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_get_supdiamond.png"/>
    <item label="btn_green" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_green.png"/>
    <item label="btn_guild" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_guild.png"/>
    <item label="btn_guild_lock" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_guild_lock.png"/>
    <item label="btn_halidom" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_halidom.png"/>
    <item label="btn_halidom_highlight" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_halidom_highlight.png"/>
    <item label="btn_heroes" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_heroes.png"/>
    <item label="btn_heroes_highlight" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_heroes_highlight.png"/>
    <item label="btn_leave_war" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_leave_war.png"/>
    <item label="btn_mail_off" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_mail_off.png"/>
    <item label="btn_mail_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_mail_on.png"/>
    <item label="btn_main_close" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_main_close.png"/>
    <item label="btn_main_max" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_main_max.png"/>
    <item label="btn_main_min" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_main_min.png"/>
    <item label="btn_master" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_master.png"/>
    <item label="btn_master_highlight" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_master_highlight.png"/>
    <item label="btn_match" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_match.png"/>
    <item label="btn_match_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_match_on.png"/>
    <item label="btn_match_red" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_match_red.png"/>
    <item label="btn_new_player" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_new_player.png"/>
    <item label="btn_offonlinecoin" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_offonlinecoin.png"/>
    <item label="btn_orange" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_orange.png"/>
    <item label="btn_pk" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_pk.png"/>
    <item label="btn_pk_close" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_pk_close.png"/>
    <item label="btn_pop_blue" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_pop_blue.png"/>
    <item label="btn_pop_disabled" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_pop_disabled.png"/>
    <item label="btn_pop_orange" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_pop_orange.png"/>
    <item label="btn_rank" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_rank.png"/>
    <item label="btn_rank_best" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_rank_best.png"/>
    <item label="btn_rank_blue" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_rank_blue.png"/>
    <item label="btn_rank_green" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_rank_green.png"/>
    <item label="btn_select_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_select_bg.png"/>
    <item label="btn_select_open" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_select_open.png"/>
    <item label="btn_setting" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_setting.png"/>
    <item label="btn_share" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_share.png"/>
    <item label="btn_shop" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_shop.png"/>
    <item label="btn_shop_highlight" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_shop_highlight.png"/>
    <item label="btn_skill1" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill1.png"/>
    <item label="btn_skill2" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill2.png"/>
    <item label="btn_skill3" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill3.png"/>
    <item label="btn_skill4" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill4.png"/>
    <item label="btn_skill5" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill5.png"/>
    <item label="btn_skill6" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill6.png"/>
    <item label="btn_skill_disabled" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_skill_disabled.png"/>
    <item label="btn_task" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_task.png"/>
    <item label="btn_task_hava" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_task_hava.png"/>
    <item label="btn_weapon" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_weapon.png"/>
    <item label="btn_yellow" file="/Users/workspace/taptitans/client/res_raw/texture/common/btn_yellow.png"/>
    <item label="coin" file="/Users/workspace/taptitans/client/res_raw/texture/common/coin.png"/>
    <item label="common_bosstime" file="/Users/workspace/taptitans/client/res_raw/texture/common/common_bosstime.png"/>
    <item label="crystal" file="/Users/workspace/taptitans/client/res_raw/texture/common/crystal.png"/>
    <item label="dailyTaskEnterBtn" file="/Users/workspace/taptitans/client/res_raw/texture/common/dailyTaskEnterBtn.png"/>
    <item label="dailyTaskGained" file="/Users/workspace/taptitans/client/res_raw/texture/common/dailyTaskGained.png"/>
    <item label="dailyTaskTitleIcon" file="/Users/workspace/taptitans/client/res_raw/texture/common/dailyTaskTitleIcon.png"/>
    <item label="diamond" file="/Users/workspace/taptitans/client/res_raw/texture/common/diamond.png"/>
    <item label="dps_info_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/dps_info_bg.png"/>
    <item label="effect_coinbtn" file="/Users/workspace/taptitans/client/res_raw/texture/common/effect_coinbtn.png"/>
    <item label="fragment" file="/Users/workspace/taptitans/client/res_raw/texture/common/fragment.png"/>
    <item label="icon_buy_artifact" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_buy_artifact.png"/>
    <item label="icon_buy_artifact_all" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_buy_artifact_all.png"/>
    <item label="icon_crystal" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_crystal.png"/>
    <item label="icon_default" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_default.png"/>
    <item label="icon_disabled" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_disabled.png"/>
    <item label="icon_fragment" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_fragment.png"/>
    <item label="icon_giftbag" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_giftbag.png"/>
    <item label="icon_hand" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_hand.png"/>
    <item label="icon_loading" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_loading.png"/>
    <item label="icon_lvup_weapon" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_lvup_weapon.png"/>
    <item label="icon_mail_default" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_mail_default.png"/>
    <item label="icon_match_player" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_match_player.png"/>
    <item label="icon_monster" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_monster.png"/>
    <item label="icon_name_line" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_name_line.png"/>
    <item label="icon_prestige" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_prestige.png"/>
    <item label="icon_select_gold_heroes" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_select_gold_heroes.png"/>
    <item label="icon_small_prestige_artifact" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_small_prestige_artifact.png"/>
    <item label="icon_small_prestige_weapon" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_small_prestige_weapon.png"/>
    <item label="icon_weapons" file="/Users/workspace/taptitans/client/res_raw/texture/common/icon_weapons.png"/>
    <item label="list_element_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/list_element_bg.png"/>
    <item label="morale" file="/Users/workspace/taptitans/client/res_raw/texture/common/morale.png"/>
    <item label="platform" file="/Users/workspace/taptitans/client/res_raw/texture/common/platform.png"/>
    <item label="progress_bar" file="/Users/workspace/taptitans/client/res_raw/texture/common/progress_bar.png"/>
    <item label="progress_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/progress_bg.png"/>
    <item label="rank_btn_back" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_btn_back.png"/>
    <item label="rank_btn_visit" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_btn_visit.png"/>
    <item label="rank_line" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_line.png"/>
    <item label="rank_num1" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_num1.png"/>
    <item label="rank_num2" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_num2.png"/>
    <item label="rank_num3" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_num3.png"/>
    <item label="rank_point" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_point.png"/>
    <item label="rank_title_bar" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_title_bar.png"/>
    <item label="rank_topbtn_att_off" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_att_off.png"/>
    <item label="rank_topbtn_att_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_att_on.png"/>
    <item label="rank_topbtn_friend_off" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_friend_off.png"/>
    <item label="rank_topbtn_friend_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_friend_on.png"/>
    <item label="rank_topbtn_world_off" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_world_off.png"/>
    <item label="rank_topbtn_world_on" file="/Users/workspace/taptitans/client/res_raw/texture/common/rank_topbtn_world_on.png"/>
    <item label="relic" file="/Users/workspace/taptitans/client/res_raw/texture/common/relic.png"/>
    <item label="scrollview_bg1" file="/Users/workspace/taptitans/client/res_raw/texture/common/scrollview_bg1.png"/>
    <item label="sharewx" file="/Users/workspace/taptitans/client/res_raw/texture/common/sharewx.png"/>
    <item label="stage_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/stage_bg.png"/>
    <item label="stage_icon" file="/Users/workspace/taptitans/client/res_raw/texture/common/stage_icon.png"/>
    <item label="submap10_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap10_1.png"/>
    <item label="submap10_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap10_2.png"/>
    <item label="submap10_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap10_3.png"/>
    <item label="submap10_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap10_4.png"/>
    <item label="submap10_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap10_5.png"/>
    <item label="submap1_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap1_1.png"/>
    <item label="submap1_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap1_2.png"/>
    <item label="submap1_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap1_3.png"/>
    <item label="submap1_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap1_4.png"/>
    <item label="submap1_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap1_5.png"/>
    <item label="submap2_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap2_1.png"/>
    <item label="submap2_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap2_2.png"/>
    <item label="submap2_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap2_3.png"/>
    <item label="submap2_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap2_4.png"/>
    <item label="submap2_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap2_5.png"/>
    <item label="submap3_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap3_1.png"/>
    <item label="submap3_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap3_2.png"/>
    <item label="submap3_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap3_3.png"/>
    <item label="submap3_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap3_4.png"/>
    <item label="submap3_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap3_5.png"/>
    <item label="submap4_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap4_1.png"/>
    <item label="submap4_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap4_2.png"/>
    <item label="submap4_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap4_3.png"/>
    <item label="submap4_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap4_4.png"/>
    <item label="submap4_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap4_5.png"/>
    <item label="submap5_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap5_1.png"/>
    <item label="submap5_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap5_2.png"/>
    <item label="submap5_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap5_3.png"/>
    <item label="submap5_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap5_4.png"/>
    <item label="submap5_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap5_5.png"/>
    <item label="submap6_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap6_1.png"/>
    <item label="submap6_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap6_2.png"/>
    <item label="submap6_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap6_3.png"/>
    <item label="submap6_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap6_4.png"/>
    <item label="submap6_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap6_5.png"/>
    <item label="submap7_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap7_1.png"/>
    <item label="submap7_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap7_2.png"/>
    <item label="submap7_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap7_3.png"/>
    <item label="submap7_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap7_4.png"/>
    <item label="submap7_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap7_5.png"/>
    <item label="submap8_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap8_1.png"/>
    <item label="submap8_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap8_2.png"/>
    <item label="submap8_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap8_3.png"/>
    <item label="submap8_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap8_4.png"/>
    <item label="submap8_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap8_5.png"/>
    <item label="submap9_1" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap9_1.png"/>
    <item label="submap9_2" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap9_2.png"/>
    <item label="submap9_3" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap9_3.png"/>
    <item label="submap9_4" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap9_4.png"/>
    <item label="submap9_5" file="/Users/workspace/taptitans/client/res_raw/texture/common/submap9_5.png"/>
    <item label="tip_big_task" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_big_task.png"/>
    <item label="tip_discount_50" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_discount_50.png"/>
    <item label="tip_double" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_double.png"/>
    <item label="tip_hero_dead" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_hero_dead.png"/>
    <item label="tip_hero_tombstone" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_hero_tombstone.png"/>
    <item label="tip_hot" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_hot.png"/>
    <item label="tip_new" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_new.png"/>
    <item label="tip_sale" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_sale.png"/>
    <item label="tip_task" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_task.png"/>
    <item label="tip_weapon_count_bg" file="/Users/workspace/taptitans/client/res_raw/texture/common/tip_weapon_count_bg.png"/>
    <item label="token_monster" file="/Users/workspace/taptitans/client/res_raw/texture/common/token_monster.png"/>
  </items>
</root>