<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="true" canvasSize="1016,799"/>
  <items>
    <item label="equip_buy_armor1" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor1.png"/>
    <item label="equip_buy_armor2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor2.png"/>
    <item label="equip_buy_armor3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor3.png"/>
    <item label="equip_buy_armor4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor4.png"/>
    <item label="equip_buy_armor5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor5.png"/>
    <item label="equip_buy_armor6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor6.png"/>
    <item label="equip_buy_armor7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor7.png"/>
    <item label="equip_buy_armor8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor8.png"/>
    <item label="equip_buy_armor9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor9.png"/>
    <item label="equip_buy_armor10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor10.png"/>
    <item label="equip_buy_armor11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor11.png"/>
    <item label="equip_buy_armor12" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor12.png"/>
    <item label="equip_buy_armor13" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor13.png"/>
    <item label="equip_buy_armor14" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor14.png"/>
    <item label="equip_buy_armor15" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor15.png"/>
    <item label="equip_buy_armor16" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor16.png"/>
    <item label="equip_buy_armor17" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor17.png"/>
    <item label="equip_buy_armor18" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_armor18.png"/>
    <item label="equip_buy_headpiece1" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece1.png"/>
    <item label="equip_buy_headpiece2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece2.png"/>
    <item label="equip_buy_headpiece3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece3.png"/>
    <item label="equip_buy_headpiece4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece4.png"/>
    <item label="equip_buy_headpiece5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece5.png"/>
    <item label="equip_buy_headpiece6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece6.png"/>
    <item label="equip_buy_headpiece7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece7.png"/>
    <item label="equip_buy_headpiece8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece8.png"/>
    <item label="equip_buy_headpiece9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece9.png"/>
    <item label="equip_buy_headpiece10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece10.png"/>
    <item label="equip_buy_headpiece11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece11.png"/>
    <item label="equip_buy_headpiece12" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece12.png"/>
    <item label="equip_buy_headpiece13" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece13.png"/>
    <item label="equip_buy_headpiece14" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_headpiece14.png"/>
    <item label="equip_buy_mantle1" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle1.png"/>
    <item label="equip_buy_mantle2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle2.png"/>
    <item label="equip_buy_mantle3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle3.png"/>
    <item label="equip_buy_mantle4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle4.png"/>
    <item label="equip_buy_mantle5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle5.png"/>
    <item label="equip_buy_mantle6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle6.png"/>
    <item label="equip_buy_mantle7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle7.png"/>
    <item label="equip_buy_mantle8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle8.png"/>
    <item label="equip_buy_mantle9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle9.png"/>
    <item label="equip_buy_mantle10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle10.png"/>
    <item label="equip_buy_mantle11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle11.png"/>
    <item label="equip_buy_mantle12" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle12.png"/>
    <item label="equip_buy_mantle13" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_mantle13.png"/>
    <item label="equip_buy_sword1" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword1.png"/>
    <item label="equip_buy_sword2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword2.png"/>
    <item label="equip_buy_sword3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword3.png"/>
    <item label="equip_buy_sword4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword4.png"/>
    <item label="equip_buy_sword5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword5.png"/>
    <item label="equip_buy_sword6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword6.png"/>
    <item label="equip_buy_sword7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword7.png"/>
    <item label="equip_buy_sword8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword8.png"/>
    <item label="equip_buy_sword9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword9.png"/>
    <item label="equip_buy_sword10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword10.png"/>
    <item label="equip_buy_sword11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword11.png"/>
    <item label="equip_buy_sword12" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_sword12.png"/>
    <item label="equip_buy_weapon1" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon1.png"/>
    <item label="equip_buy_weapon2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon2.png"/>
    <item label="equip_buy_weapon3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon3.png"/>
    <item label="equip_buy_weapon4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon4.png"/>
    <item label="equip_buy_weapon5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon5.png"/>
    <item label="equip_buy_weapon6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon6.png"/>
    <item label="equip_buy_weapon7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon7.png"/>
    <item label="equip_buy_weapon8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon8.png"/>
    <item label="equip_buy_weapon9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon9.png"/>
    <item label="equip_buy_weapon10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon10.png"/>
    <item label="equip_buy_weapon11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon11.png"/>
    <item label="equip_buy_weapon12" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon12.png"/>
    <item label="equip_buy_weapon13" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon13.png"/>
    <item label="equip_buy_weapon14" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon14.png"/>
    <item label="equip_buy_weapon15" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon15.png"/>
    <item label="equip_buy_weapon16" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon16.png"/>
    <item label="equip_buy_weapon17" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon17.png"/>
    <item label="equip_buy_weapon18" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon18.png"/>
    <item label="equip_buy_weapon19" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon19.png"/>
    <item label="equip_buy_weapon20" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon20.png"/>
    <item label="equip_buy_weapon21" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon21.png"/>
    <item label="equip_buy_weapon22" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon22.png"/>
    <item label="equip_buy_weapon23" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon23.png"/>
    <item label="equip_buy_weapon24" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon24.png"/>
    <item label="equip_buy_weapon25" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon25.png"/>
    <item label="equip_buy_weapon26" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon26.png"/>
    <item label="equip_buy_weapon27" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon27.png"/>
    <item label="equip_buy_weapon28" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon28.png"/>
    <item label="equip_buy_weapon29" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon29.png"/>
    <item label="equip_buy_weapon30" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon30.png"/>
    <item label="equip_buy_weapon31" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon31.png"/>
    <item label="equip_buy_weapon32" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_weapon32.png"/>
    <item label="equip_buy_wing2" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing2.png"/>
    <item label="equip_buy_wing3" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing3.png"/>
    <item label="equip_buy_wing4" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing4.png"/>
    <item label="equip_buy_wing5" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing5.png"/>
    <item label="equip_buy_wing6" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing6.png"/>
    <item label="equip_buy_wing7" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing7.png"/>
    <item label="equip_buy_wing8" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing8.png"/>
    <item label="equip_buy_wing9" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing9.png"/>
    <item label="equip_buy_wing10" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing10.png"/>
    <item label="equip_buy_wing11" file="/Users/workspace/taptitans/client/res_raw/texture/equip/equip_buy_wing11.png"/>
  </items>
</root>
