<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="true" canvasSize="1020,480"/>
  <items>
    <item label="equip_armor1" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor1.png"/>
    <item label="equip_armor2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor2.png"/>
    <item label="equip_armor3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor3.png"/>
    <item label="equip_armor4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor4.png"/>
    <item label="equip_armor5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor5.png"/>
    <item label="equip_armor6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor6.png"/>
    <item label="equip_armor7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor7.png"/>
    <item label="equip_armor8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor8.png"/>
    <item label="equip_armor9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor9.png"/>
    <item label="equip_armor10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor10.png"/>
    <item label="equip_armor11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor11.png"/>
    <item label="equip_armor12" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor12.png"/>
    <item label="equip_armor13" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor13.png"/>
    <item label="equip_armor14" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor14.png"/>
    <item label="equip_armor15" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor15.png"/>
    <item label="equip_armor16" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor16.png"/>
    <item label="equip_armor17" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor17.png"/>
    <item label="equip_armor18" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_armor18.png"/>
    <item label="equip_headpiece1" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece1.png"/>
    <item label="equip_headpiece2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece2.png"/>
    <item label="equip_headpiece3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece3.png"/>
    <item label="equip_headpiece4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece4.png"/>
    <item label="equip_headpiece5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece5.png"/>
    <item label="equip_headpiece6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece6.png"/>
    <item label="equip_headpiece7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece7.png"/>
    <item label="equip_headpiece8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece8.png"/>
    <item label="equip_headpiece9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece9.png"/>
    <item label="equip_headpiece10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece10.png"/>
    <item label="equip_headpiece11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece11.png"/>
    <item label="equip_headpiece12" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece12.png"/>
    <item label="equip_headpiece13" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece13.png"/>
    <item label="equip_headpiece14" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_headpiece14.png"/>
    <item label="equip_mantle1" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle1.png"/>
    <item label="equip_mantle2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle2.png"/>
    <item label="equip_mantle3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle3.png"/>
    <item label="equip_mantle4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle4.png"/>
    <item label="equip_mantle5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle5.png"/>
    <item label="equip_mantle6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle6.png"/>
    <item label="equip_mantle7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle7.png"/>
    <item label="equip_mantle8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle8.png"/>
    <item label="equip_mantle9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle9.png"/>
    <item label="equip_mantle10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle10.png"/>
    <item label="equip_mantle11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle11.png"/>
    <item label="equip_mantle12" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle12.png"/>
    <item label="equip_mantle13" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_mantle13.png"/>
    <item label="equip_sword1" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword1.png"/>
    <item label="equip_sword2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword2.png"/>
    <item label="equip_sword3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword3.png"/>
    <item label="equip_sword4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword4.png"/>
    <item label="equip_sword5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword5.png"/>
    <item label="equip_sword6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword6.png"/>
    <item label="equip_sword7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword7.png"/>
    <item label="equip_sword8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword8.png"/>
    <item label="equip_sword9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword9.png"/>
    <item label="equip_sword10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword10.png"/>
    <item label="equip_sword11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword11.png"/>
    <item label="equip_sword12" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_sword12.png"/>
    <item label="equip_weapon1" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon1.png"/>
    <item label="equip_weapon2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon2.png"/>
    <item label="equip_weapon3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon3.png"/>
    <item label="equip_weapon4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon4.png"/>
    <item label="equip_weapon5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon5.png"/>
    <item label="equip_weapon6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon6.png"/>
    <item label="equip_weapon7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon7.png"/>
    <item label="equip_weapon8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon8.png"/>
    <item label="equip_weapon9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon9.png"/>
    <item label="equip_weapon10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon10.png"/>
    <item label="equip_weapon11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon11.png"/>
    <item label="equip_weapon12" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon12.png"/>
    <item label="equip_weapon13" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon13.png"/>
    <item label="equip_weapon14" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon14.png"/>
    <item label="equip_weapon15" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon15.png"/>
    <item label="equip_weapon16" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon16.png"/>
    <item label="equip_weapon17" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon17.png"/>
    <item label="equip_weapon18" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon18.png"/>
    <item label="equip_weapon19" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon19.png"/>
    <item label="equip_weapon20" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon20.png"/>
    <item label="equip_weapon21" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon21.png"/>
    <item label="equip_weapon22" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon22.png"/>
    <item label="equip_weapon23" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon23.png"/>
    <item label="equip_weapon24" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon24.png"/>
    <item label="equip_weapon25" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon25.png"/>
    <item label="equip_weapon26" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon26.png"/>
    <item label="equip_weapon27" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon27.png"/>
    <item label="equip_weapon28" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon28.png"/>
    <item label="equip_weapon29" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon29.png"/>
    <item label="equip_weapon30" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon30.png"/>
    <item label="equip_weapon31" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon31.png"/>
    <item label="equip_weapon32" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_weapon32.png"/>
    <item label="equip_wing2" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing2.png"/>
    <item label="equip_wing3" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing3.png"/>
    <item label="equip_wing4" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing4.png"/>
    <item label="equip_wing5" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing5.png"/>
    <item label="equip_wing6" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing6.png"/>
    <item label="equip_wing7" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing7.png"/>
    <item label="equip_wing8" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing8.png"/>
    <item label="equip_wing9" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing9.png"/>
    <item label="equip_wing10" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing10.png"/>
    <item label="equip_wing11" file="/Users/workspace/taptitans/client/res_raw/texture/equipitem/equip_wing11.png"/>
  </items>
</root>
