<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="true" canvasSize="1024,488"/>
  <items>
    <item label="shop9" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop9.png"/>
    <item label="shop10" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop10.png"/>
    <item label="shop11" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop11.png"/>
    <item label="shop12" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop12.png"/>
    <item label="shop13" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop13.png"/>
    <item label="shop14" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop14.png"/>
    <item label="shop15" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop15.png"/>
    <item label="artifact30" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact30.png"/>
    <item label="item_coin" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/item_coin.png"/>
    <item label="item_relic" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/item_relic.png"/>
    <item label="shop6" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop6.png"/>
    <item label="shop7" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop7.png"/>
    <item label="shop8" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop8.png"/>
    <item label="artifact1" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact1.png"/>
    <item label="artifact2" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact2.png"/>
    <item label="artifact3" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact3.png"/>
    <item label="artifact4" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact4.png"/>
    <item label="artifact5" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact5.png"/>
    <item label="artifact6" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact6.png"/>
    <item label="artifact7" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact7.png"/>
    <item label="artifact8" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact8.png"/>
    <item label="artifact9" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact9.png"/>
    <item label="artifact10" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact10.png"/>
    <item label="artifact11" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact11.png"/>
    <item label="artifact12" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact12.png"/>
    <item label="artifact13" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact13.png"/>
    <item label="artifact14" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact14.png"/>
    <item label="artifact15" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact15.png"/>
    <item label="artifact16" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact16.png"/>
    <item label="artifact17" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact17.png"/>
    <item label="artifact18" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact18.png"/>
    <item label="artifact19" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact19.png"/>
    <item label="artifact20" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact20.png"/>
    <item label="artifact21" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact21.png"/>
    <item label="artifact22" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact22.png"/>
    <item label="artifact23" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact23.png"/>
    <item label="artifact24" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact24.png"/>
    <item label="artifact25" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact25.png"/>
    <item label="artifact26" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact26.png"/>
    <item label="artifact27" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact27.png"/>
    <item label="artifact28" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact28.png"/>
    <item label="artifact29" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/artifact29.png"/>
    <item label="hero1" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero1.png"/>
    <item label="hero2" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero2.png"/>
    <item label="hero3" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero3.png"/>
    <item label="hero4" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero4.png"/>
    <item label="hero5" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero5.png"/>
    <item label="hero6" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero6.png"/>
    <item label="hero7" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero7.png"/>
    <item label="hero8" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero8.png"/>
    <item label="hero9" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero9.png"/>
    <item label="hero10" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero10.png"/>
    <item label="hero11" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero11.png"/>
    <item label="hero12" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero12.png"/>
    <item label="hero13" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero13.png"/>
    <item label="hero14" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero14.png"/>
    <item label="hero15" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero15.png"/>
    <item label="hero16" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero16.png"/>
    <item label="hero17" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero17.png"/>
    <item label="hero18" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero18.png"/>
    <item label="hero19" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero19.png"/>
    <item label="hero20" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero20.png"/>
    <item label="hero21" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero21.png"/>
    <item label="hero22" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero22.png"/>
    <item label="hero23" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero23.png"/>
    <item label="hero24" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero24.png"/>
    <item label="hero25" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero25.png"/>
    <item label="hero26" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero26.png"/>
    <item label="hero27" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero27.png"/>
    <item label="hero28" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero28.png"/>
    <item label="hero29" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero29.png"/>
    <item label="hero30" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero30.png"/>
    <item label="hero31" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero31.png"/>
    <item label="hero32" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero32.png"/>
    <item label="hero33" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/hero33.png"/>
    <item label="icon_skill7" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill7.png"/>
    <item label="shop1" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop1.png"/>
    <item label="shop2" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop2.png"/>
    <item label="shop3" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop3.png"/>
    <item label="shop4" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop4.png"/>
    <item label="shop5" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/shop5.png"/>
    <item label="achievement1" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement1.png"/>
    <item label="achievement2" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement2.png"/>
    <item label="achievement3" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement3.png"/>
    <item label="achievement4" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement4.png"/>
    <item label="achievement5" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement5.png"/>
    <item label="achievement6" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement6.png"/>
    <item label="achievement7" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement7.png"/>
    <item label="achievement8" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement8.png"/>
    <item label="achievement9" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement9.png"/>
    <item label="achievement10" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement10.png"/>
    <item label="achievement11" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement11.png"/>
    <item label="achievement12" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement12.png"/>
    <item label="achievement13" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement13.png"/>
    <item label="achievement14" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/achievement14.png"/>
    <item label="icon_skill1" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill1.png"/>
    <item label="icon_skill2" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill2.png"/>
    <item label="icon_skill3" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill3.png"/>
    <item label="icon_skill4" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill4.png"/>
    <item label="icon_skill5" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill5.png"/>
    <item label="icon_skill6" file="/Users/workspace/taptitans/client/res_raw/texture/iconItem/icon_skill6.png"/>
  </items>
</root>
