<root>
  <app layoutGap="1" useExtension="false" cutImage="true" layoutMath="2" autoLayout="true" freeSize="true" canvasSize="998,1059"/>
  <items>
    <item label="heroskill19_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_1.png"/>
    <item label="heroskill19_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_2.png"/>
    <item label="heroskill19_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_3.png"/>
    <item label="heroskill19_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_4.png"/>
    <item label="heroskill19_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_5.png"/>
    <item label="heroskill19_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_6.png"/>
    <item label="heroskill19_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill19_7.png"/>
    <item label="heroskill26_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_1.png"/>
    <item label="heroskill26_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_2.png"/>
    <item label="heroskill26_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_3.png"/>
    <item label="heroskill26_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_4.png"/>
    <item label="heroskill26_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_5.png"/>
    <item label="heroskill26_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_6.png"/>
    <item label="heroskill26_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill26_7.png"/>
    <item label="heroskill_evolution" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill_evolution.png"/>
    <item label="heroskill1_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_1.png"/>
    <item label="heroskill1_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_2.png"/>
    <item label="heroskill1_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_3.png"/>
    <item label="heroskill1_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_4.png"/>
    <item label="heroskill1_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_5.png"/>
    <item label="heroskill1_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_6.png"/>
    <item label="heroskill1_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill1_7.png"/>
    <item label="heroskill2_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_1.png"/>
    <item label="heroskill2_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_2.png"/>
    <item label="heroskill2_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_3.png"/>
    <item label="heroskill2_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_4.png"/>
    <item label="heroskill2_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_5.png"/>
    <item label="heroskill2_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_6.png"/>
    <item label="heroskill2_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill2_7.png"/>
    <item label="heroskill3_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_1.png"/>
    <item label="heroskill3_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_2.png"/>
    <item label="heroskill3_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_3.png"/>
    <item label="heroskill3_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_4.png"/>
    <item label="heroskill3_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_5.png"/>
    <item label="heroskill3_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_6.png"/>
    <item label="heroskill3_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill3_7.png"/>
    <item label="heroskill4_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_1.png"/>
    <item label="heroskill4_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_2.png"/>
    <item label="heroskill4_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_3.png"/>
    <item label="heroskill4_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_4.png"/>
    <item label="heroskill4_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_5.png"/>
    <item label="heroskill4_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_6.png"/>
    <item label="heroskill4_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill4_7.png"/>
    <item label="heroskill5_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_1.png"/>
    <item label="heroskill5_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_2.png"/>
    <item label="heroskill5_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_3.png"/>
    <item label="heroskill5_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_4.png"/>
    <item label="heroskill5_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_5.png"/>
    <item label="heroskill5_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_6.png"/>
    <item label="heroskill5_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill5_7.png"/>
    <item label="heroskill6_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_1.png"/>
    <item label="heroskill6_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_2.png"/>
    <item label="heroskill6_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_3.png"/>
    <item label="heroskill6_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_4.png"/>
    <item label="heroskill6_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_5.png"/>
    <item label="heroskill6_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_6.png"/>
    <item label="heroskill6_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill6_7.png"/>
    <item label="heroskill7_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_1.png"/>
    <item label="heroskill7_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_2.png"/>
    <item label="heroskill7_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_3.png"/>
    <item label="heroskill7_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_4.png"/>
    <item label="heroskill7_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_5.png"/>
    <item label="heroskill7_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_6.png"/>
    <item label="heroskill7_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill7_7.png"/>
    <item label="heroskill8_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_1.png"/>
    <item label="heroskill8_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_2.png"/>
    <item label="heroskill8_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_3.png"/>
    <item label="heroskill8_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_4.png"/>
    <item label="heroskill8_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_5.png"/>
    <item label="heroskill8_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_6.png"/>
    <item label="heroskill8_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill8_7.png"/>
    <item label="heroskill9_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_1.png"/>
    <item label="heroskill9_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_2.png"/>
    <item label="heroskill9_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_3.png"/>
    <item label="heroskill9_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_4.png"/>
    <item label="heroskill9_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_5.png"/>
    <item label="heroskill9_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_6.png"/>
    <item label="heroskill9_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill9_7.png"/>
    <item label="heroskill10_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_1.png"/>
    <item label="heroskill10_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_2.png"/>
    <item label="heroskill10_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_3.png"/>
    <item label="heroskill10_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_4.png"/>
    <item label="heroskill10_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_5.png"/>
    <item label="heroskill10_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_6.png"/>
    <item label="heroskill10_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill10_7.png"/>
    <item label="heroskill11_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_1.png"/>
    <item label="heroskill11_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_2.png"/>
    <item label="heroskill11_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_3.png"/>
    <item label="heroskill11_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_4.png"/>
    <item label="heroskill11_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_5.png"/>
    <item label="heroskill11_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_6.png"/>
    <item label="heroskill11_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill11_7.png"/>
    <item label="heroskill12_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_1.png"/>
    <item label="heroskill12_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_2.png"/>
    <item label="heroskill12_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_3.png"/>
    <item label="heroskill12_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_4.png"/>
    <item label="heroskill12_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_5.png"/>
    <item label="heroskill12_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_6.png"/>
    <item label="heroskill12_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill12_7.png"/>
    <item label="heroskill13_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_1.png"/>
    <item label="heroskill13_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_2.png"/>
    <item label="heroskill13_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_3.png"/>
    <item label="heroskill13_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_4.png"/>
    <item label="heroskill13_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_5.png"/>
    <item label="heroskill13_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_6.png"/>
    <item label="heroskill13_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill13_7.png"/>
    <item label="heroskill14_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_1.png"/>
    <item label="heroskill14_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_2.png"/>
    <item label="heroskill14_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_3.png"/>
    <item label="heroskill14_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_4.png"/>
    <item label="heroskill14_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_5.png"/>
    <item label="heroskill14_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_6.png"/>
    <item label="heroskill14_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill14_7.png"/>
    <item label="heroskill15_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_1.png"/>
    <item label="heroskill15_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_2.png"/>
    <item label="heroskill15_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_3.png"/>
    <item label="heroskill15_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_4.png"/>
    <item label="heroskill15_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_5.png"/>
    <item label="heroskill15_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_6.png"/>
    <item label="heroskill15_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill15_7.png"/>
    <item label="heroskill16_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_1.png"/>
    <item label="heroskill16_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_2.png"/>
    <item label="heroskill16_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_3.png"/>
    <item label="heroskill16_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_4.png"/>
    <item label="heroskill16_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_5.png"/>
    <item label="heroskill16_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_6.png"/>
    <item label="heroskill16_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill16_7.png"/>
    <item label="heroskill17_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_1.png"/>
    <item label="heroskill17_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_2.png"/>
    <item label="heroskill17_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_3.png"/>
    <item label="heroskill17_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_4.png"/>
    <item label="heroskill17_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_5.png"/>
    <item label="heroskill17_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_6.png"/>
    <item label="heroskill17_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill17_7.png"/>
    <item label="heroskill18_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_1.png"/>
    <item label="heroskill18_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_2.png"/>
    <item label="heroskill18_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_3.png"/>
    <item label="heroskill18_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_4.png"/>
    <item label="heroskill18_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_5.png"/>
    <item label="heroskill18_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_6.png"/>
    <item label="heroskill18_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill18_7.png"/>
    <item label="heroskill20_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_1.png"/>
    <item label="heroskill20_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_2.png"/>
    <item label="heroskill20_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_3.png"/>
    <item label="heroskill20_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_4.png"/>
    <item label="heroskill20_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_5.png"/>
    <item label="heroskill20_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_6.png"/>
    <item label="heroskill20_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill20_7.png"/>
    <item label="heroskill21_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_1.png"/>
    <item label="heroskill21_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_2.png"/>
    <item label="heroskill21_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_3.png"/>
    <item label="heroskill21_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_4.png"/>
    <item label="heroskill21_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_5.png"/>
    <item label="heroskill21_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_6.png"/>
    <item label="heroskill21_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill21_7.png"/>
    <item label="heroskill22_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_1.png"/>
    <item label="heroskill22_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_2.png"/>
    <item label="heroskill22_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_3.png"/>
    <item label="heroskill22_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_4.png"/>
    <item label="heroskill22_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_5.png"/>
    <item label="heroskill22_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_6.png"/>
    <item label="heroskill22_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill22_7.png"/>
    <item label="heroskill23_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_1.png"/>
    <item label="heroskill23_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_2.png"/>
    <item label="heroskill23_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_3.png"/>
    <item label="heroskill23_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_4.png"/>
    <item label="heroskill23_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_5.png"/>
    <item label="heroskill23_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_6.png"/>
    <item label="heroskill23_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill23_7.png"/>
    <item label="heroskill24_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_1.png"/>
    <item label="heroskill24_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_2.png"/>
    <item label="heroskill24_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_3.png"/>
    <item label="heroskill24_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_4.png"/>
    <item label="heroskill24_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_5.png"/>
    <item label="heroskill24_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_6.png"/>
    <item label="heroskill24_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill24_7.png"/>
    <item label="heroskill25_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_1.png"/>
    <item label="heroskill25_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_2.png"/>
    <item label="heroskill25_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_3.png"/>
    <item label="heroskill25_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_4.png"/>
    <item label="heroskill25_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_5.png"/>
    <item label="heroskill25_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_6.png"/>
    <item label="heroskill25_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill25_7.png"/>
    <item label="heroskill27_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_1.png"/>
    <item label="heroskill27_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_2.png"/>
    <item label="heroskill27_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_3.png"/>
    <item label="heroskill27_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_4.png"/>
    <item label="heroskill27_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_5.png"/>
    <item label="heroskill27_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_6.png"/>
    <item label="heroskill27_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill27_7.png"/>
    <item label="heroskill28_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_1.png"/>
    <item label="heroskill28_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_2.png"/>
    <item label="heroskill28_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_3.png"/>
    <item label="heroskill28_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_4.png"/>
    <item label="heroskill28_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_5.png"/>
    <item label="heroskill28_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_6.png"/>
    <item label="heroskill28_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill28_7.png"/>
    <item label="heroskill29_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_1.png"/>
    <item label="heroskill29_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_2.png"/>
    <item label="heroskill29_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_3.png"/>
    <item label="heroskill29_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_4.png"/>
    <item label="heroskill29_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_5.png"/>
    <item label="heroskill29_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_6.png"/>
    <item label="heroskill29_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill29_7.png"/>
    <item label="heroskill30_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_1.png"/>
    <item label="heroskill30_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_2.png"/>
    <item label="heroskill30_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_3.png"/>
    <item label="heroskill30_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_4.png"/>
    <item label="heroskill30_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_5.png"/>
    <item label="heroskill30_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_6.png"/>
    <item label="heroskill30_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill30_7.png"/>
    <item label="heroskill31_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_1.png"/>
    <item label="heroskill31_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_2.png"/>
    <item label="heroskill31_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_3.png"/>
    <item label="heroskill31_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_4.png"/>
    <item label="heroskill31_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_5.png"/>
    <item label="heroskill31_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_6.png"/>
    <item label="heroskill31_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill31_7.png"/>
    <item label="heroskill32_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_1.png"/>
    <item label="heroskill32_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_2.png"/>
    <item label="heroskill32_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_3.png"/>
    <item label="heroskill32_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_4.png"/>
    <item label="heroskill32_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_5.png"/>
    <item label="heroskill32_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_6.png"/>
    <item label="heroskill32_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill32_7.png"/>
    <item label="heroskill33_1" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_1.png"/>
    <item label="heroskill33_2" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_2.png"/>
    <item label="heroskill33_3" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_3.png"/>
    <item label="heroskill33_4" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_4.png"/>
    <item label="heroskill33_5" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_5.png"/>
    <item label="heroskill33_6" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_6.png"/>
    <item label="heroskill33_7" file="/Users/workspace/taptitans/client/res_raw/texture/heroskill/heroskill33_7.png"/>
  </items>
</root>
